### ISSUE TITLE
Issue with OAuth 1.0a and add Authorization in Request Headers

### ISSUE THREAD

**Issue by maxherson** [postmanlabs/newman#1052]
Version and environment information:

 1. Newman Version (can be found via `newman -v`): 3.5.2
 2. OS details (type, version, and architecture): Win 10 64
 3. Are you using Newman as a library, or via the CLI? via the CLI
 3. Did you encounter this recently, or has this bug always been there: always
 4. Expected behaviour: 
 5. Command / script used to run Newman: newman run api_reg2.postman_collection.json -e max_stage_api_auto.postman_environment.json -d All_brand.csv
 6. Sample collection, and auxilliary files (minus the sensitive details):
 7. Screenshots (if applicable): https://goo.gl/Qrlh3C POST work good BUT GET 401

Looks like it don't send Authorization in Request Headers

**Comment by maxherson** [comment]
That is how my collection looks like GET with Authorization  https://goo.gl/OqDEPY

**Comment by maxherson** [comment]
In the POSTMAN with "Add params to header" checkbox  https://goo.gl/J7t6cH looks good
Without it https://goo.gl/tTBcpL

**Comment by gornialberto** [comment]
If i try to use in the pre-request script btoa() methods i'm getting this error:

There was an error in evaluating the Pre-request Script:  TypeError: btoa is not a function

Before the Postman last update it was working!!

**Comment by kunagpal** [comment]
@maxherson If this issue persists for you with the latest versions of the app (5.0.2) and Newman (3.7.4), would you also mind sharing collections with both: Save params to header turned on, as well as off? Feel free to exclude sensitive details.

@gornialberto Your issue is distinct from this one, please open up a new issue here: https://github.com/postmanlabs/postman-app-support/issues/new if it still doesn't work with v5.0.2 of the app.

**Comment by maxherson** [comment]
We find out issue, I clone POST with body, then change it to GET body was hidden BUT after export collection body was there for GET request. This is the reason.
